/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportExportRouteImport } from './routes/import-export'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as EngagementIndexRouteImport } from './routes/engagement.index'
import { Route as SettingsChurchRouteImport } from './routes/settings.church'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalContributionsRouteImport } from './routes/portal.contributions'
import { Route as MembersArchiveRouteImport } from './routes/members.archive'
import { Route as MembersMemberIdRouteImport } from './routes/members.$memberId'
import { Route as EngagementVisitsRouteImport } from './routes/engagement.visits'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportExportRoute = ImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementIndexRoute = EngagementIndexRouteImport.update({
  id: '/engagement/',
  path: '/engagement/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsChurchRoute = SettingsChurchRouteImport.update({
  id: '/settings/church',
  path: '/settings/church',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContributionsRoute = PortalContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => PortalRoute,
} as any)
const MembersArchiveRoute = MembersArchiveRouteImport.update({
  id: '/members/archive',
  path: '/members/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementVisitsRoute = EngagementVisitsRouteImport.update({
  id: '/engagement/visits',
  path: '/engagement/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/portal': typeof PortalRouteWithChildren
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/engagement/visits': typeof EngagementVisitsRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/archive': typeof MembersArchiveRoute
  '/portal/contributions': typeof PortalContributionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/settings/church': typeof SettingsChurchRoute
  '/engagement/': typeof EngagementIndexRoute
  '/members/': typeof MembersIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/engagement/visits': typeof EngagementVisitsRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/archive': typeof MembersArchiveRoute
  '/portal/contributions': typeof PortalContributionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/settings/church': typeof SettingsChurchRoute
  '/engagement': typeof EngagementIndexRoute
  '/members': typeof MembersIndexRoute
  '/portal': typeof PortalIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/portal': typeof PortalRouteWithChildren
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/engagement/visits': typeof EngagementVisitsRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/archive': typeof MembersArchiveRoute
  '/portal/contributions': typeof PortalContributionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/settings/church': typeof SettingsChurchRoute
  '/engagement/': typeof EngagementIndexRoute
  '/members/': typeof MembersIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/import-export'
    | '/login'
    | '/pending'
    | '/portal'
    | '/reports'
    | '/reset-password'
    | '/signup'
    | '/engagement/visits'
    | '/members/$memberId'
    | '/members/archive'
    | '/portal/contributions'
    | '/portal/profile'
    | '/settings/church'
    | '/engagement/'
    | '/members/'
    | '/portal/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/import-export'
    | '/login'
    | '/pending'
    | '/reports'
    | '/reset-password'
    | '/signup'
    | '/engagement/visits'
    | '/members/$memberId'
    | '/members/archive'
    | '/portal/contributions'
    | '/portal/profile'
    | '/settings/church'
    | '/engagement'
    | '/members'
    | '/portal'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/import-export'
    | '/login'
    | '/pending'
    | '/portal'
    | '/reports'
    | '/reset-password'
    | '/signup'
    | '/engagement/visits'
    | '/members/$memberId'
    | '/members/archive'
    | '/portal/contributions'
    | '/portal/profile'
    | '/settings/church'
    | '/engagement/'
    | '/members/'
    | '/portal/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImportExportRoute: typeof ImportExportRoute
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  PortalRoute: typeof PortalRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  EngagementVisitsRoute: typeof EngagementVisitsRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  MembersArchiveRoute: typeof MembersArchiveRoute
  SettingsChurchRoute: typeof SettingsChurchRoute
  EngagementIndexRoute: typeof EngagementIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-export': {
      id: '/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof ImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement/': {
      id: '/engagement/'
      path: '/engagement'
      fullPath: '/engagement/'
      preLoaderRoute: typeof EngagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/church': {
      id: '/settings/church'
      path: '/settings/church'
      fullPath: '/settings/church'
      preLoaderRoute: typeof SettingsChurchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contributions': {
      id: '/portal/contributions'
      path: '/contributions'
      fullPath: '/portal/contributions'
      preLoaderRoute: typeof PortalContributionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/members/archive': {
      id: '/members/archive'
      path: '/members/archive'
      fullPath: '/members/archive'
      preLoaderRoute: typeof MembersArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement/visits': {
      id: '/engagement/visits'
      path: '/engagement/visits'
      fullPath: '/engagement/visits'
      preLoaderRoute: typeof EngagementVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalContributionsRoute: typeof PortalContributionsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalContributionsRoute: PortalContributionsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImportExportRoute: ImportExportRoute,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  PortalRoute: PortalRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  EngagementVisitsRoute: EngagementVisitsRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  MembersArchiveRoute: MembersArchiveRoute,
  SettingsChurchRoute: SettingsChurchRoute,
  EngagementIndexRoute: EngagementIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
